[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "source /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Skipping collectstatic'"]

[start]
cmd = "source /opt/venv/bin/activate && python manage.py migrate && gunicorn CowTrack.wsgi:application --bind 0.0.0.0:$PORT --log-level debug --access-logfile - --error-logfile -" 