# Generated by Django 4.2.23 on 2025-06-26 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cow_number', models.CharField(max_length=20, unique=True, verbose_name='牛番号')),
                ('shed_code', models.CharField(max_length=10, verbose_name='牛舎番号')),
                ('intake_date', models.DateField(blank=True, null=True, verbose_name='導入日')),
                ('gender', models.CharField(choices=[('castrated', '去勢'), ('female', 'メス')], default='female', max_length=10)),
                ('origin_region', models.CharField(blank=True, max_length=50, null=True, verbose_name='導入元地域')),
                ('status', models.CharField(choices=[('active', '活動中'), ('inactive', '非活動')], default='active', max_length=10, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '牛',
                'verbose_name_plural': '牛',
            },
        ),
        migrations.CreateModel(
            name='FeedingObservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observed_at', models.DateTimeField()),
                ('appetite', models.CharField(blank=True, choices=[('○', '○'), ('△', '△'), ('×', '×'), ('-', '-')], max_length=1, null=True)),
                ('symptoms', models.CharField(blank=True, max_length=255, null=True)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment_status', models.CharField(choices=[('untreated', '未治療'), ('re_examination', '再診'), ('self_treatment', '自己治療'), ('follow_up', '経過観察')], default='untreated', max_length=20, verbose_name='治療状況')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.cow')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '餌観察記録',
                'verbose_name_plural': '餌観察記録',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='薬剤名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '薬剤',
                'verbose_name_plural': '薬剤',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_date', models.DateTimeField(verbose_name='治療日時')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='診断')),
                ('treatment_content', models.TextField(verbose_name='治療内容')),
                ('treatment_type', models.CharField(choices=[('initial', '初回治療'), ('follow_up', '経過観察'), ('emergency', '緊急治療')], default='initial', max_length=20, verbose_name='治療種別')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.cow', verbose_name='対象牛')),
                ('primary_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='主治療担当者')),
            ],
            options={
                'verbose_name': '治療履歴',
                'verbose_name_plural': '治療履歴',
            },
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='獣医師名')),
                ('license_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='獣医師免許番号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '獣医師',
                'verbose_name_plural': '獣医師',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('re_examination', '再診'), ('self_treatment', '自己治療'), ('follow_up', '経過観察')], max_length=20, verbose_name='治療結果')),
                ('follow_up_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='経過観察日数')),
                ('diagnosis', models.TextField(blank=True, verbose_name='診断内容')),
                ('treatment_content', models.TextField(blank=True, verbose_name='治療内容')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feeding_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.feedingobservation', verbose_name='餌観察記録')),
                ('treatment_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='治療担当者')),
            ],
            options={
                'verbose_name': '治療結果',
                'verbose_name_plural': '治療結果',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dosage_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='投薬日数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.medicine', verbose_name='薬剤')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.treatment', verbose_name='治療履歴')),
            ],
            options={
                'verbose_name': '治療薬剤',
                'verbose_name_plural': '治療薬剤',
            },
        ),
        migrations.AddField(
            model_name='treatment',
            name='veterinarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cattle.veterinarian', verbose_name='獣医師'),
        ),
        migrations.CreateModel(
            name='MovementLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_shed_code', models.CharField(blank=True, max_length=4, null=True)),
                ('to_shed_code', models.CharField(max_length=4)),
                ('moved_at', models.DateField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.cow')),
                ('moved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpObservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observed_at', models.DateTimeField()),
                ('appetite', models.CharField(blank=True, choices=[('○', '○'), ('△', '△'), ('×', '×'), ('-', '-')], max_length=1, null=True)),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.treatment')),
            ],
            options={
                'verbose_name': '経過観察',
                'verbose_name_plural': '経過観察',
            },
        ),
        migrations.CreateModel(
            name='DailyVeterinarian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='日付')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='主治療担当者')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.veterinarian', verbose_name='獣医師')),
            ],
            options={
                'verbose_name': '日別獣医師設定',
                'verbose_name_plural': '日別獣医師設定',
                'ordering': ['-date'],
            },
        ),
    ]
