# Generated by Django 4.2.23 on 2025-06-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_cow_gender_alter_user_first_name_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow',
            name='last5_digits',
        ),
    ]
