# Generated by Django 4.2.23 on 2025-06-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0003_remove_cow_last5_digits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'get_latest_by': 'treatment_date'},
        ),
        migrations.AddField(
            model_name='treatment',
            name='medication',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='投薬'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='治療内容'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='veterinarian',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='獣医師'),
        ),
    ]
