# Generated by Django 4.2.23 on 2025-06-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0004_alter_treatment_options_treatment_medication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='medication',
        ),
    ]
