# Generated by Django 4.2.23 on 2025-06-21 01:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0005_remove_treatment_medication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cow',
            options={'verbose_name': '牛', 'verbose_name_plural': '牛'},
        ),
        migrations.AlterModelOptions(
            name='feedingobservation',
            options={'verbose_name': '餌観察記録', 'verbose_name_plural': '餌観察記録'},
        ),
        migrations.AlterModelOptions(
            name='followupobservation',
            options={'verbose_name': '経過観察', 'verbose_name_plural': '経過観察'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': '薬剤', 'verbose_name_plural': '薬剤'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name': '治療履歴', 'verbose_name_plural': '治療履歴'},
        ),
        migrations.AlterModelOptions(
            name='treatmentmedicine',
            options={'verbose_name': '治療薬剤', 'verbose_name_plural': '治療薬剤'},
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='default_days',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='body_temperature',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='follow_up_days',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='veterinarian',
        ),
        migrations.AddField(
            model_name='cow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('initial', '初回治療'), ('follow_up', '経過観察'), ('emergency', '緊急治療')], default='initial', max_length=20, verbose_name='治療種別'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='treatmentmedicine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cow',
            name='cow_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='牛番号'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='intake_date',
            field=models.DateField(blank=True, null=True, verbose_name='導入日'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='origin_region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='導入元地域'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='shed_code',
            field=models.CharField(max_length=10, verbose_name='牛舎番号'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='status',
            field=models.CharField(choices=[('active', '活動中'), ('inactive', '非活動')], default='active', max_length=10, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='薬剤名'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='cow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.cow', verbose_name='対象牛'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='diagnosis',
            field=models.CharField(default='', max_length=255, verbose_name='診断'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='獣医師'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='備考'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_content',
            field=models.TextField(default='', verbose_name='治療内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_date',
            field=models.DateTimeField(verbose_name='治療日時'),
        ),
        migrations.AlterField(
            model_name='treatmentmedicine',
            name='dosage_days',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='投薬日数'),
        ),
        migrations.AlterField(
            model_name='treatmentmedicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.medicine', verbose_name='薬剤'),
        ),
        migrations.AlterField(
            model_name='treatmentmedicine',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.treatment', verbose_name='治療履歴'),
        ),
        migrations.CreateModel(
            name='DailyVeterinarian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='日付')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='獣医師')),
            ],
            options={
                'verbose_name': '日別獣医師設定',
                'verbose_name_plural': '日別獣医師設定',
                'ordering': ['-date'],
            },
        ),
    ]
