# Generated by Django 4.2.23 on 2025-06-21 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0006_alter_cow_options_alter_feedingobservation_options_and_more'),
    ]

    operations = [
        # 獣医師マスタモデルの作成
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='獣医師名')),
                ('license_number', models.CharField(max_length=20, unique=True, verbose_name='獣医師免許番号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '獣医師',
                'verbose_name_plural': '獣医師',
                'ordering': ['name'],
            },
        ),
        
        # Treatmentモデルの更新
        migrations.AddField(
            model_name='treatment',
            name='veterinarian',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='cattle.veterinarian',
                verbose_name='獣医師',
                null=True  # 一時的にnullを許可
            ),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_doctor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='cattle.user',
                verbose_name='主治療担当者'
            ),
        ),
        
        # DailyVeterinarianモデルの更新
        migrations.AddField(
            model_name='dailyveterinarian',
            name='primary_doctor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='cattle.user',
                verbose_name='主治療担当者'
            ),
        ),
    ]
