# Generated by Django 4.2.23 on 2025-06-21 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0007_auto_20250621_1110'),
    ]

    operations = [
    ]
