# Generated by Django 4.2.23 on 2025-06-21 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0008_auto_20250621_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='dailyveterinarian',
            name='veterinarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.veterinarian', verbose_name='獣医師'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='veterinarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cattle.veterinarian', verbose_name='獣医師'),
        ),
    ]
