# Generated by Django 4.2.23 on 2025-06-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0009_remove_treatment_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarian',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='獣医師免許番号'),
        ),
    ]
