# Generated by Django 4.2.23 on 2025-06-21 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0010_alter_veterinarian_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingobservation',
            name='treatment_status',
            field=models.CharField(choices=[('untreated', '未治療'), ('re_examination', '再診'), ('self_treatment', '自己治療'), ('follow_up', '経過観察')], default='untreated', max_length=20, verbose_name='治療状況'),
        ),
        migrations.CreateModel(
            name='TreatmentResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('re_examination', '再診'), ('self_treatment', '自己治療'), ('follow_up', '経過観察')], max_length=20, verbose_name='治療結果')),
                ('diagnosis', models.TextField(blank=True, verbose_name='診断内容')),
                ('treatment_content', models.TextField(blank=True, verbose_name='治療内容')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feeding_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.feedingobservation', verbose_name='餌観察記録')),
                ('treatment_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='治療担当者')),
            ],
            options={
                'verbose_name': '治療結果',
                'verbose_name_plural': '治療結果',
                'ordering': ['-created_at'],
            },
        ),
    ]
