# Generated by Django 4.2.23 on 2025-06-21 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0011_feedingobservation_treatment_status_treatmentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentresult',
            name='follow_up_days',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='経過観察日数'),
        ),
    ]
